-- [[ plug.lua ]]
--     -- Plugins go here
--     -- [[ Dev ]]
--     use { 'luukvbaal/nnn.nvim' }
-- 
--     -- [[ Conjure for REPL ]]
--     use { 'Olical/conjure' }
--     use { 'guns/vim-sexp' }
-- 
-- 
--     -- -- DAP Plugins
--     use { "mfussenegger/nvim-dap" }
--     use { "mfussenegger/nvim-dap-python" }
--     use { "rcarriga/nvim-dap-ui" }
--     use { "theHamsta/nvim-dap-virtual-text" }
--     -- use { "nvim-telescope/telescope-dap.nvim" }
--     --
--     use {
--     "nvim-neorg/neorg",
--     config = function()
--         require('neorg').setup {
--             load = {
--                 ["core.defaults"] = {}, -- Loads default behaviour
--                 ["core.concealer"] = {}, -- Adds pretty icons to your documents
--                 ["core.dirman"] = { -- Manages Neorg workspaces
--                     config = {
--                         workspaces = {
--                             notes = "~/notes",
--                         },
--                     },
--                 },
--             },
--         }
--     end,
--     run = ":Neorg sync-parsers",
--     requires = "nvim-lua/plenary.nvim",
-- }
--  end)
-- 
