-- [[ plug.lua ]]
-- return require('packer').startup(function(use)
--     -- Plugins go here
--     -- [[ Dev ]]
--     use { 'hrsh7th/nvim-cmp' }
--     use { 'hrsh7th/cmp-nvim-lsp' }
--     use { 'saadparwaiz1/cmp_luasnip' }
--     use {
--         'numToStr/Comment.nvim',
--         config = function ()
--             require ('Comment').setup()
-- 	end
--     }
--     use {
--         'nvimdev/lspsaga.nvim',
--         after = "nvim-lspconfig",
--         config = function()
--             require("lspsaga")
--         end,
--     }
--     use { 'nvimtools/none-ls.nvim' }
--     use { 'jay-babu/mason-null-ls.nvim' }
--     use { 'luukvbaal/nnn.nvim' }
--     use { 'folke/trouble.nvim' }
-- 
--     -- [[ Conjure for REPL ]]
--     use { 'Olical/conjure' }
--     use { 'guns/vim-sexp' }
-- 
-- 
--     -- -- DAP Plugins
--     use { "mfussenegger/nvim-dap" }
--     use { "mfussenegger/nvim-dap-python" }
--     use { "rcarriga/nvim-dap-ui" }
--     use { "theHamsta/nvim-dap-virtual-text" }
--     -- use { "nvim-telescope/telescope-dap.nvim" }
--     --
--     use {
--     "nvim-neorg/neorg",
--     config = function()
--         require('neorg').setup {
--             load = {
--                 ["core.defaults"] = {}, -- Loads default behaviour
--                 ["core.concealer"] = {}, -- Adds pretty icons to your documents
--                 ["core.dirman"] = { -- Manages Neorg workspaces
--                     config = {
--                         workspaces = {
--                             notes = "~/notes",
--                         },
--                     },
--                 },
--             },
--         }
--     end,
--     run = ":Neorg sync-parsers",
--     requires = "nvim-lua/plenary.nvim",
-- }
--  end)
-- 
